name: tstore_dart
description: A dart library that helps you to manage and store entity objects.
version: 0.3.4
homepage: https://github.com/tyrcord/tstore_dart
issue_tracker: https://github.com/tyrcord/tstore_dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  rxdart: ^0.27.1
  meta: ^1.3.0
  equatable: ^2.0.3
  tmodel_dart: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  test: ^1.16.8
  dart_code_metrics: ^4.0.1
