name: tstore_dart
description: A dart library that helps you to store objects.
version: 0.1.0
author: Tyrcord, Inc.
homepage: https://github.com/tyrcord/tstore_dart
issue_tracker: https://github.com/tyrcord/tstore_dart/issues

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  rxdart: ^0.24.1
  meta: ^1.2.3

dev_dependencies:
  hive_generator: ^0.8.1
  build_runner: ^1.10.3
