name: tstore_dart
description: A dart library that helps you to manage and store entity and model objects.
version: 0.1.2
homepage: https://github.com/tyrcord/tstore_dart
issue_tracker: https://github.com/tyrcord/tstore_dart/issues

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  rxdart: ^0.24.1
  meta: ^1.2.3
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  test: ^1.15.7
  dart_code_metrics: ^2.3.1
